### ISSUE TITLE
[plugin] add plugin that will allow definition generation from interfaces incrementally

### ISSUE THREAD

**Issue by gelidus** [flowup/mmo#32]
This will require implementing an algorithm that will skip all already-defined methods.

Example:
```
type TodoServiceServer interface {
	GetVersion(context.Context, *google_protobuf.Empty) (*Version, error)
	AddTodoITtem(context.Context, *TodoRequest) (*TodoRequest, error)
	RemoveTodoItem(context.Context, *TodoRequest) (*google_protobuf.Empty, error)
}
```

Will generate an implementation of this interface in a given output file for all methods.

However, if we add another method to the interface,
`GetAll(context.Context, *google_protobuf.Empty) (*TodoList, error)`

we can simply regenerate the interface with the plugin, creating only this added method in an output file.

**Comment by kubaj** [comment]
Implemented in mmo-plugins/gen-interfaces
