### ISSUE TITLE
[docs] add core project features and roadmap

### ISSUE THREAD

**Issue by petomalina** [flowup/mmo#42]
MMO should have a well-defined roadmap and core features that we'll always provide. This will allow both FlowUp and community around it to help with creation of plugins and orchestration design.

## Updated release schedule
Alpha - August 16.(wed) 2017
Beta - October 18.(wed) 2017

**One liners**
- **Micro-service orchestrator that removes devops**
- **Micro-service orchestrator with devops baked-in**
- **Easily create and deploy micro-services**

**Core features**
- project initialization
- service manipulation (adding, removing)
- local development
- local integration environment
- deploy
- pluggable
  - generators
  - deploy targets
  - development cycles

## Roadmap:
**Alpha**
- project management and orchestration
- an initial release of plugins
- multiple generators (proto, dao, grpc, rest gateway, webrpc)

**Beta**
- deployment management
- CI pipeline
- integration with Calchas (so Calchas can derive any CI pipeline from the MMO configuration)
- plugins for multiple stages (init, dev, test, etc.)
- initial Python support

**First Release**
- stability along > 5 projects
- full support for Go and Python

**UI Release (dashboard)**
- initial support for MMO UI
- support to view all resources within the project and deployments

**Management UI Release**
- ability to manage generation, tests, deployments, orchestration etc. using UI

**Comment by kubaj** [comment]
**Beta**
- final version of advanced plugin system
  - plugins should be capable of different actions such as generating code, testing code, building, deploying, etc
  - configurations - some plugins may need additional stuff such as credentials to cluster, ...
  - this should improve support of new languages and technologies in future -> mmo has integrated generation of golang services, for adding new language support we've to have to add generators to mmo, while with plugins, new language can be added only with set of plugins
  - global plugins and per-service plugins
- deployment management
- CI pipeline
- integration with Calchas (so Calchas can derive any CI pipeline from the MMO configuration)
- initial Python support

**Comment by gelidus** [comment]
Ad. `this should improve support for new languages and technologies in future`. Yes, however, we need a good way to distinguish between language-dependent plugins and others (k8s, ...). Any ideas about this?

Ad. `global plugins and per-service plugins` all plugins should definitely be per-service. MMO is indeed monorepo orchestrator, however, it should be really easy to move some service to a standalone repo. We should discuss this feature more.

CI pipeline should IMHO trigger all stages of MMO - generate, build, test, deploy (with optional flag). The trigger can be:
```
mmo ci --deploy # to run with deploy
```

**Comment by gelidus** [comment]
Updated releases to:
Alpha - August 16.(wed) 2017
Beta - October 18.(wed) 2017

We should consider 2 month releases as stable at the moment. We'll see how will Beta go
