### ISSUE TITLE
[gen] Global Context

### ISSUE THREAD

**Issue by Dasio** [flowup/mmo#46]
When using global context, 'gen' doesn't work
                    
- WARN[0000] No context set, using global                 
- INFO[0004] Running hook 'gen' of plugin Go gRPC generator 
- =/hooks/gen.sh: 6: cd: can't cd to /source/converter/protobuf

But with specified context, everything works as expected
- INFO[0004] Running hook 'gen' of plugin Go gRPC generator 
- CGenerating gRPC server and stubs from protofile for service engine

**Comment by gelidus** [comment]
@Dasio can you please add step-by-step commands?

**Comment by Dasio** [comment]
Using at dashly-goldfish
1. mmo ctx --reset
2. mmo gen

There are errors:
`=/hooks/gen.sh: 6: cd: can't cd to /source/converter/protobuf`
`'proto.proto: No such file or directory
`
There is probably something wrong with converter service, there is no proto file, so nothing should be generated anyway.
Should I add something to mmo.yaml to ignore gen for service ?
Anyway in case of error skip that service and continue ?

1. mmo ctx engine
2. mmo gen

Everything works as expected

**Comment by gelidus** [comment]
that will be the case. MMO supports only GRPC services at the moment. However, we should also be able to disable support in the future, to allow writing e.g. HTTP services, etc. @kubaj

**Comment by kubaj** [comment]
This is resolved by #56 

Each service has its own set of plugins so there shouldn't be conflicts like this one
