### ISSUE TITLE
[config] Update config according to MMO Beta proposal

### ISSUE THREAD

**Issue by kubaj** [flowup/mmo#54]
Sections below will be removed:
* lang
* dependencyManager
* goPackage
* plugins
* service/x/
  * webRPC
  * sentry
  * gateway

The new property will be added:
* default service generator - name of the image that generates new service in project

**Comment by gelidus** [comment]
@kubaj can you please share status of this issue?

**Comment by kubaj** [comment]
Config is updated in #56
