### ISSUE TITLE
Collecting user experience reports

### ISSUE THREAD

**Issue by gelidus** [flowup/mmo#60]
Please leave your experience reports as comments in this issue.

Current UX reports are based on the e2e quickstart guide #59

**Comment by bafko** [comment]
- missing `mmo add service` parameters (e.g. `-x Gateway=true`)
- missing brief plugin description
- there already is a good quickstart guide - **Example usage** in [README.md](https://github.com/flowup/mmo/blob/v0.2/README.md)

**Comment by gelidus** [comment]
- `mmo init` - there is no feedback, only `Bootstrap successful`. As a user, I have no idea what just happened. We should add more logs
- `mmo init` - there is a wercker.yml within the project when first created. We may want to avoid adding these CI tools (even though we first thought it will be a good idea)
- `mmo add service <name>` - no feedback to the user, only `Bootstrap successful`
- there is no way to tell how does one actually build stuff with mmo

Looks like all logs just disappeared for me. There is always just `[info]` without any message (but bootstrap message works)

TBH, I would be pretty much scared to death as a user, as I have no idea what just happened to the environment I am in.

**Comment by gelidus** [comment]
Closing this as beta reports are now done. More feedback was collected from discussions.
