### ISSUE TITLE
[all/ux] create logging and error reporting standard

### ISSUE THREAD

**Issue by gelidus** [flowup/mmo#64]
We should create a wiki page describing logging and error reporting standard used in mmo and mmo-plugins, so all plugins will have same errors outputs and logging capabilities.

We will be accepting proposals on this issue. 

TODO: link to wiki

- [x] research existing tools and their logs/error reporting
- [x] research best practices for cli ux
- [x] create logging level standard (4 levels would be great, from debug to error)
- [x] document logrus log.WithFields and what should be included every time
- [x] create example user-facing CLI function and document its logging
- [x] create plugin logging standard (what should be logged for each plugin)

**Comment by tomas2707** [comment]
It is recommended to use the logging standard in following levels:
1) DEBUG - provides debugging messages to us, if it is turn on.
2) INFO - Anything that we want to know, when a scheduled job started/ended.
3) WARN - Any message that might warn us of potential problems
4) ERROR - Any error/exception that is or might be critical.

**Comment by gelidus** [comment]
@tomas2707 please create a wiki page containing this information.
