### ISSUE TITLE
mmo add service fails with: Failed to fire hook: raven got http 429

### ISSUE THREAD

**Issue by petomalina** [flowup/mmo#84]
This looks like the project is still using old raven for error reporting. We should remove this capability and replace it with something like "report error" when it crashes. Removing raven will be enough for now

```
 peto@peto  ~/go/src/github.com/petomalina/mmotest  mmo add service
Failed to fire hook: raven: got http status 429
ERRO[0000] No arguments 
```

**Comment by kubaj** [comment]
True, but that also says that there is another bug - docker status check
fail shouldn't be reported to sentry.

**Comment by petomalina** [comment]
I already removed Sentry in the commit above, but we need to create a better docker check here. @rysavyvladan can you please look into that?
